Ext.define('MyApp.view.todos.Todos',{
    extend:'Ext.panel.Panel',
    xtype:'todos',
    viewModel:{
        data:{
            record:null
        }
    },
    items:[
        {
            xtype:'todogrid'
        },
        {
            xtype:'todoDetails'
        }
    ]
})